language: node_js
node_js:
  - "8"
addons:
  sauce_connect: true
  direct_domains: bol.com
  username: "Your Sauce Labs username"
  access_key: "Your Sauce Labs access key"

before_script:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - nohup selenium-standalone start
script:
  - npm test