language: node_js
node_js:
  - "8"
addons:
  sauce_connect: true
  direct_domains: bol.com
  username: "Your Sauce Labs username"
  access_key: "Your Sauce Labs access key"
before_install:
- npm install selenium-standalone@latest -g
- selenium-standalone install

before_script:
- nohup selenium-standalone start > selenium.txt 2>&1 </dev/null &
- sleep 15

script:
  - npm test